// Code generated by goctl. DO NOT EDIT.
package {{.pkgName}}

import (
    {{if .hasMiddleware}}"{{.rootPkg}}/middleware"{{end}}

	"github.com/gin-gonic/gin"
	"github.com/go-admin-team/go-admin-core/sdk/pkg/jwtauth"
)

func Register{{.funcName}}Route(r *gin.RouterGroup, authMiddleware *jwtauth.GinJWTMiddleware) {
    api := api.NewAdmin{{.funcName}}Api()
    record := r.Group("{{if .hasPrefix}}{{.prefix}}{{end}}"){{if .hasMiddleware}}
    r.Use({{range .middleware}}middleware.{{.}}, {{end}}){{end}}
    {{- range .routes}}
    r.{{.method}}("{{.path}}", {{$.handleBase}}.{{.handle}}Handle)
    {{- end}}
}